version: '3.3'

services:
  backend:
    restart: always
    build: ./backend
    environment:
      - REDIS_HOST=redis
      - CACHE_SECONDS=14400  # 4 hours

  web:
    restart: always
    build: ./web

  rev-proxy:
    restart: always
    build: ./rev-proxy
    ports:
      - 5000:80
    depends_on:
      - web
      - backend

  redis:
    restart: always
    image: redis:4-alpine
